import fs from 'fs/promises';
import path from 'path';
import { spawn } from 'child_process';
import puppeteer from 'puppeteer';
import { config } from '../config.js';
import { AppError } from '../utils/errors.js';
import { parseNetscapeCookies, USER_AGENT } from '../utils/cookies.js';
import {
  buildYtdlpBaseArgs,
  datacenterBlockDetail,
  hasPotBypass,
  isDatacenterBotBlock,
} from '../utils/ytdlp.js';

const COOKIE_MAX_AGE_HOURS = Number(config.cookiesMaxAgeHours) || 12;
const AUTH_COOKIE_NAMES = new Set([
  'LOGIN_INFO',
  '__Secure-1PSID',
  '__Secure-3PSID',
  'SID',
  'HSID',
  'SSID',
]);
const YOUTUBE_PROBE_URL = 'https://www.youtube.com/watch?v=jNQXAC9IVRw';
const BROWSER_EXPORT_ORDER = (config.cookiesBrowsers || 'chrome,edge,chromium,brave,firefox')
  .split(',')
  .map((b) => b.trim())
  .filter(Boolean);

const EXTENSION_URL =
  'https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc';

let refreshInFlight = null;

export function cookiesExpiredMessage(
  cookiesPath = config.cookiesPath,
  detail = '',
) {
  const base =
    `YouTube login could not be refreshed automatically. ` +
    `Sign in once in the browser window that opens when you analyze, or export cookies manually ` +
    `(extension: Get cookies.txt LOCALLY) to: ${cookiesPath}`;
  return detail ? `${base}\n\n${detail}` : base;
}

export function throwCookiesExpired(cookiesPath = config.cookiesPath, detail = '') {
  const raw = typeof detail === 'string' ? detail : detail?.message || '';
  if (isDatacenterBotBlock(raw, { hasAuthCookies: true }) && !hasPotBypass()) {
    throw new AppError(datacenterBlockDetail(), 401, 'YOUTUBE_DATACENTER_BLOCK');
  }
  throw new AppError(cookiesExpiredMessage(cookiesPath, detail), 401, 'COOKIES_EXPIRED');
}

function throwDatacenterBlock() {
  throw new AppError(datacenterBlockDetail(), 401, 'YOUTUBE_DATACENTER_BLOCK');
}

export function isSignInError(message) {
  const msg = String(message || '');
  return /sign in to confirm|sign in|not a bot|login required|cookies.*invalid|authentication|confirm you're not a bot|use --cookies-from-browser|http error 403|unable to download|requested content is not available|this content is not available/i.test(
    msg,
  );
}

/** Quick yt-dlp check: cookies.txt still works for YouTube (not just file age). */
export function probeYoutubeCookiesFile(cookiesPath = config.cookiesPath) {
  const ytdlpPath = config.ytdlpPath;
  return new Promise((resolve, reject) => {
    let stderr = '';
    const proc = spawn(
      ytdlpPath,
      buildYtdlpBaseArgs([
        '--cookies',
        cookiesPath,
        '--skip-download',
        '--no-warnings',
        '--print',
        'id',
        YOUTUBE_PROBE_URL,
      ]),
    );

    proc.stderr.on('data', (d) => {
      stderr += d.toString();
    });
    proc.on('close', (code) => {
      if (code === 0) resolve(true);
      else reject(new Error(stderr.trim() || `yt-dlp probe exited ${code}`));
    });
    proc.on('error', reject);
  });
}

function toNetscapeFormat(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.haxx.se/rfc/cookie_spec.html',
    '# Generated by Videclip',
  ];

  const fallbackExpiry = Math.floor(Date.now() / 1000) + 86400 * 365;

  for (const cookie of cookies) {
    if (!cookie.name || cookie.value === undefined) continue;

    let domain = cookie.domain || '.youtube.com';
    const hostOnly = !domain.startsWith('.');
    if (!hostOnly && !domain.startsWith('.')) {
      domain = `.${domain}`;
    }

    const cookiePath = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = Math.floor(
      cookie.expires && cookie.expires > 0 ? cookie.expires : fallbackExpiry,
    );

    lines.push(
      [
        domain,
        hostOnly ? 'FALSE' : 'TRUE',
        cookiePath,
        secure,
        expires,
        cookie.name,
        cookie.value,
      ].join('\t'),
    );
  }

  return `${lines.join('\n')}\n`;
}

export function hasAuthenticatedYoutubeCookies(rawOrCookies) {
  const cookies =
    typeof rawOrCookies === 'string'
      ? parseNetscapeCookies(rawOrCookies)
      : rawOrCookies;
  return cookies.some(
    (c) =>
      AUTH_COOKIE_NAMES.has(c.name) &&
      /\.youtube\.com$|youtube\.com$/i.test(c.domain || ''),
  );
}

async function readCookiesRaw(cookiesPath) {
  try {
    return await fs.readFile(cookiesPath, 'utf8');
  } catch {
    return null;
  }
}

export async function getCookiesAgeHours(cookiesPath = config.cookiesPath) {
  try {
    const stats = await fs.stat(cookiesPath);
    return (Date.now() - stats.mtimeMs) / 3600000;
  } catch {
    return Infinity;
  }
}

async function shouldRefreshCookies(cookiesPath = config.cookiesPath) {
  const raw = await readCookiesRaw(cookiesPath);
  if (!raw) return true;
  if (!hasAuthenticatedYoutubeCookies(raw)) return true;
  const ageHours = await getCookiesAgeHours(cookiesPath);
  return ageHours >= COOKIE_MAX_AGE_HOURS;
}

function runYtdlpCookieExport(browser, cookiesPath) {
  const ytdlpPath = config.ytdlpPath;
  return new Promise((resolve, reject) => {
    let stderr = '';
    const proc = spawn(
      ytdlpPath,
      buildYtdlpBaseArgs([
        '--cookies-from-browser',
        browser,
        '--cookies',
        cookiesPath,
        '--skip-download',
        '--no-warnings',
        '--print',
        'title',
        YOUTUBE_PROBE_URL,
      ]),
    );

    proc.stderr.on('data', (d) => {
      stderr += d.toString();
    });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(stderr.trim() || `yt-dlp exited ${code}`));
    });
    proc.on('error', reject);
  });
}

function shortCookieError(message) {
  const line = String(message || '')
    .split('\n')
    .find((l) => l.trim()) || 'unknown error';
  return line.replace(/^ERROR:\s*/i, '').slice(0, 160);
}

async function exportCookiesFromInstalledBrowsers(cookiesPath) {
  if (config.cookiesSkipBrowserExport || !BROWSER_EXPORT_ORDER.length) {
    console.log('[cookies] Skipping browser export (using Puppeteer profile only)');
    return false;
  }

  await fs.mkdir(path.dirname(cookiesPath), { recursive: true }).catch(() => {});

  const failures = [];
  for (const browser of BROWSER_EXPORT_ORDER) {
    try {
      console.log(`[cookies] Trying browser export (${browser})…`);
      await runYtdlpCookieExport(browser, cookiesPath);
      const raw = await readCookiesRaw(cookiesPath);
      if (raw && hasAuthenticatedYoutubeCookies(raw)) {
        console.log(`[cookies] Exported authenticated cookies from ${browser}`);
        return true;
      }
      console.log(`[cookies] ${browser} export had no YouTube login cookies`);
    } catch (err) {
      failures.push(`${browser}: ${shortCookieError(err.message)}`);
    }
  }

  if (failures.length) {
    console.warn(
      `[cookies] Browser export unavailable (${failures.length} tried) — ` +
        `falling back to Puppeteer. Tip: close Chrome/Edge or set COOKIES_SKIP_BROWSER_EXPORT=1`,
    );
    for (const f of failures) {
      console.warn(`[cookies]   ${f}`);
    }
  }
  return false;
}

function netscapeToPuppeteerCookies(raw) {
  return parseNetscapeCookies(raw).map((c) => {
    const domain = c.domain?.startsWith('.') ? c.domain : `.${c.domain || 'youtube.com'}`;
    const host = domain.replace(/^\./, '');
    return {
      name: c.name,
      value: c.value,
      domain,
      path: c.path || '/',
      secure: c.name.startsWith('__Secure') || c.name.startsWith('__Host'),
      httpOnly:
        c.name.startsWith('__Secure') ||
        c.name === 'LOGIN_INFO' ||
        c.name.endsWith('PSID'),
      url: `https://${host}${c.path || '/'}`,
    };
  });
}

async function waitForYoutubeLogin(page, timeoutMs = 180000) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    const cookies = await page.cookies('https://www.youtube.com', 'https://www.google.com');
    if (cookies.some((c) => AUTH_COOKIE_NAMES.has(c.name))) {
      return true;
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  return false;
}

async function refreshCookiesWithPuppeteer(cookiesPath) {
  const profileDir = config.puppeteerProfileDir;
  await fs.mkdir(profileDir, { recursive: true });

  const existingRaw = await readCookiesRaw(cookiesPath);
  const needsLogin = !existingRaw || !hasAuthenticatedYoutubeCookies(existingRaw);
  const headlessServer =
    !process.env.DISPLAY ||
    process.env.COOKIES_HEADLESS === '1' ||
    process.env.NODE_ENV === 'production';

  if (needsLogin && headlessServer) {
    throw new AppError(
      cookiesExpiredMessage(
        cookiesPath,
        'No display on this server — export cookies.txt on your PC (Get cookies.txt LOCALLY) and upload to COOKIES_PATH.',
      ),
      401,
      'COOKIES_EXPIRED',
    );
  }

  console.log(
    `[cookies] Puppeteer refresh (profile: ${profileDir}, login required: ${needsLogin}, headless: true)`,
  );

  const launchOptions = {
    headless: true,
    userDataDir: profileDir,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-blink-features=AutomationControlled',
      '--lang=en-US',
    ],
    ignoreDefaultArgs: ['--enable-automation'],
  };

  if (config.chromeExecutable) {
    launchOptions.executablePath = config.chromeExecutable;
  }

  const browser = await puppeteer.launch(launchOptions);

  try {
    const page = await browser.newPage();
    await page.setUserAgent(USER_AGENT);

    if (existingRaw) {
      const toSet = netscapeToPuppeteerCookies(existingRaw);
      if (toSet.length) {
        await page.setCookie(...toSet);
        console.log(`[cookies] Imported ${toSet.length} cookies into browser profile`);
      }
    }

    await page.goto('https://www.youtube.com', {
      waitUntil: 'networkidle2',
      timeout: 60000,
    });

    if (needsLogin) {
      const loggedIn = await waitForYoutubeLogin(page);
      if (!loggedIn) {
        throw new Error('YouTube sign-in timed out (headless)');
      }
    } else {
      await new Promise((r) => setTimeout(r, 2500));
    }

    const ytCookies = await page.cookies('https://www.youtube.com');
    const googleCookies = await page.cookies('https://www.google.com');
    const merged = new Map();
    for (const c of [...ytCookies, ...googleCookies]) {
      merged.set(`${c.domain}|${c.path}|${c.name}`, c);
    }

    const relevant = [...merged.values()].filter(
      (c) =>
        c.domain?.includes('youtube.com') ||
        c.domain?.includes('google.com') ||
        c.domain?.includes('youtu.be'),
    );

    if (!relevant.some((c) => AUTH_COOKIE_NAMES.has(c.name))) {
      throw new Error('No authenticated YouTube cookies found after browser session');
    }

    await fs.mkdir(path.dirname(cookiesPath), { recursive: true });
    await fs.writeFile(cookiesPath, toNetscapeFormat(relevant), 'utf8');
    console.log(`[cookies] Saved ${relevant.length} cookies to ${cookiesPath}`);
    return true;
  } finally {
    await browser.close().catch(() => {});
  }
}

async function doRefreshYoutubeCookies({ force = false, cookiesPath = config.cookiesPath } = {}) {
  if (!force && !(await shouldRefreshCookies(cookiesPath))) {
    const age = await getCookiesAgeHours(cookiesPath);
    console.log(`[cookies] cookies.txt still fresh (${age.toFixed(1)}h old)`);
    return { refreshed: false, cookiesPath };
  }

  console.log('[cookies] Refreshing YouTube cookies…');

  if (await exportCookiesFromInstalledBrowsers(cookiesPath)) {
    return { refreshed: true, cookiesPath, method: 'browser' };
  }

  await refreshCookiesWithPuppeteer(cookiesPath);
  console.log(`[cookies] Refresh complete (Puppeteer → ${cookiesPath})`);
  return { refreshed: true, cookiesPath, method: 'puppeteer' };
}

/** Refresh cookies if stale; throws only when automatic refresh fails. */
export async function refreshYoutubeCookies(options = {}) {
  if (refreshInFlight) return refreshInFlight;
  refreshInFlight = doRefreshYoutubeCookies(options)
    .catch((err) => {
      console.error('[cookies] Automatic refresh failed:', err.message);
      throw err;
    })
    .finally(() => {
      refreshInFlight = null;
    });
  return refreshInFlight;
}

async function cookiesFileWorks(cookiesPath) {
  try {
    await probeYoutubeCookiesFile(cookiesPath);
    return { ok: true };
  } catch (err) {
    if (isSignInError(err?.message)) {
      console.warn('[cookies] cookies.txt probe failed (login/bot):', err.message.slice(0, 120));
      return { ok: false, error: err.message };
    }
    console.warn('[cookies] cookies.txt probe inconclusive:', err.message.slice(0, 120));
    return { ok: true };
  }
}

async function maybeThrowDatacenterBlock(cookiesPath, probeError = '') {
  if (config.ytdlpPotBaseUrl || config.ytdlpProxy) {
    return false;
  }
  const raw = await readCookiesRaw(cookiesPath);
  if (!raw || !hasAuthenticatedYoutubeCookies(raw)) {
    return false;
  }
  if (isDatacenterBotBlock(probeError, { hasAuthCookies: true })) {
    console.warn('[cookies] Datacenter IP blocked by YouTube (cookies look valid)');
    throwDatacenterBlock();
  }
  return false;
}

export async function ensureFreshCookies(cookiesPath = config.cookiesPath) {
  const stale = await shouldRefreshCookies(cookiesPath);
  if (!stale) {
    const probe = await cookiesFileWorks(cookiesPath);
    if (probe.ok) {
      const age = await getCookiesAgeHours(cookiesPath);
      console.log(`[cookies] cookies.txt OK (${age.toFixed(1)}h old)`);
      return;
    }
    if (hasPotBypass()) {
      console.log(
        `[cookies] Probe inconclusive (${probe.error?.slice(0, 80) || 'unknown'}) — ` +
          'PO token/proxy configured, continuing',
      );
      return;
    }
    await maybeThrowDatacenterBlock(cookiesPath, probe.error);
    console.log('[cookies] cookies.txt rejected by YouTube — refreshing…');
  }

  try {
    await refreshYoutubeCookies({ force: true, cookiesPath });
  } catch (err) {
    if (err instanceof AppError) throw err;
    throwCookiesExpired(cookiesPath, err?.message || String(err));
  }

  const raw = await readCookiesRaw(cookiesPath);
  if (!raw || !hasAuthenticatedYoutubeCookies(raw)) {
    throwCookiesExpired(cookiesPath, 'No logged-in YouTube session after refresh.');
  }

  const probe = await cookiesFileWorks(cookiesPath);
  if (!probe.ok) {
    if (hasPotBypass()) {
      console.log('[cookies] Post-refresh probe failed — PO token/proxy configured, continuing');
      return;
    }
    await maybeThrowDatacenterBlock(cookiesPath, probe.error);
    throwCookiesExpired(cookiesPath, 'YouTube still requires sign-in after automatic refresh.');
  }
}

export { EXTENSION_URL };
